import Head from 'next/head';

const Home = ()=>{
  return (
    <>
      <Head>
        <title>Home::Media</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/images/favicon.ico" />
      </Head>
     
      
    </>
  )
}

export default Home;


